# Generated by Django 4.1.4 on 2023-03-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='First_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Last_name',
        ),
    ]
